name = "tensor-omics"
version = "0.1.0"
license = "MIT"

[install]
[install.library]
library = true
c-sources = ["src/tox_data/xxh3_hash.c"]
c-compiler = "gcc"

[library]
type = "shared" 

[build]
link = ["xxhash", "zip"]