name: 'Workflow related to Pull Requests'
description: 'Triggers all workflows needed for Pull Requests'

run_name: 'PR ${{ github.event.pull_request.number }}, Commit: ${{ github.event.pull_request.head.sha }}'

on:
  pull_request:
    paths:
      - .github/workflows/pull_requests.yml
      - .github/workflows/run_tests.yml
      - helper/generate_snippets.py
      - rcpp/**
      - python/**
      - src/**
      - test/**
      - test_runner.sh
      - build.sh
      - build_utils.sh

jobs:
  run_tests:
    strategy:
      matrix:
        compiler: [ifx, gfortran]
    uses: ./.github/workflows/run_tests.yml
    with:
      compiler: ${{ matrix.compiler }}

      # This is the commit of the PR branch head
      ref: ${{ github.event.pull_request.head.sha }}
